# Generated by Django 4.2.1 on 2023-06-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
