# Generated by Django 4.2.1 on 2023-06-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
